name: Java CI with Maven (MediaStock)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  schedule:
    - cron: '0 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration du JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilation
        run: mvn -B clean compile

      - name: Tests Unitaires
        run: mvn -B test

      - name: Création de l'exécutable (Packaging)
        run: mvn -B package -DskipTests

      - name: Archivage de l'application (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: MediaStock-App-Windows
          path: target/dist/