name: Java CI with Maven (MediaStock)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration du JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilation et Packaging (jpackage)

        run: mvn -B clean package

      - name: Archivage de l'exécutable
        uses: actions/upload-artifact@v4
        with:

          path: target/dist/